# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Nospresso' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nospresso
  pod 'R.swift'
  pod 'Nuke'

  target 'NospressoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'NospressoUITests' do
    # Pods for testing
  end

end
