# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'Forca' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Forca

  target 'ForcaTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Nimble'
    pod 'Quick'
  end

  target 'ForcaUITests' do
    # Pods for testing
  end

end
